### PR TITLE
Move binary to data-files in setup.py

### LINKED ISSUE #1: Doesn't work on Python 3
When I try to do `pip install wkhtmltopdf-pack` , I get:

```python
Collecting wkhtmltopdf-pack
  Using cached wkhtmltopdf-pack-0.12.3.0.tar.gz
Installing collected packages: wkhtmltopdf-pack
  Running setup.py install for wkhtmltopdf-pack
    Complete output from command /home/garrett/Dropbox/upcodes/upcodes/.venv/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-gkd41bcx/wkhtmltopdf-pack/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-r4idequn-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/garrett/Dropbox/upcodes/upcodes/.venv/include/site/python3.5/wkhtmltopdf-pack:
    running install
    running build
    running build_scripts
    creating build
    creating build/scripts-3.5
    Traceback (most recent call last):
      File "/home/garrett/Dropbox/upcodes/upcodes/.venv/lib/python3.5/tokenize.py", line 392, in find_cookie
        line_string = line.decode('utf-8')
    UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 24-25: invalid continuation byte
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gkd41bcx/wkhtmltopdf-pack/setup.py", line 24, in <module>
        zip_safe=False
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/garrett/Dropbox/upcodes/upcodes/.venv/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build_scripts.py", line 50, in run
        self.copy_scripts()
      File "/usr/lib/python3.5/distutils/command/build_scripts.py", line 82, in copy_scripts
        encoding, lines = tokenize.detect_encoding(f.readline)
      File "/home/garrett/Dropbox/upcodes/upcodes/.venv/lib/python3.5/tokenize.py", line 433, in detect_encoding
        encoding = find_cookie(first)
      File "/home/garrett/Dropbox/upcodes/upcodes/.venv/lib/python3.5/tokenize.py", line 397, in find_cookie
        raise SyntaxError(msg)
    

```

### PR DESCRIPTION
**Pull request by johnfraney**
Fixes #1

### CODE REVIEW

**Comment by eillarra** [comment]
Thanks! I will try to update the package this week.
Cheers, Eneko

**Comment by eillarra** [comment]
Could you squash the commits?

**Comment by johnfraney** [comment]
@eillarra Sure thing. I'll get this cleaned up

**Comment by johnfraney** [comment]
@eillarra The commit is clean now. (And sorry about the delay getting back to you about this!)

**Pull request merged**
